# Minimal _config.yml for Chirpy on GitHub Pages

theme: jekyll-theme-chirpy

# Site language and timezone
lang: en
timezone: Europe/Helsinki

# Site identity
title: "AliLatent"
tagline: "Exploring deep learning through experiments, intuition, and implementation."
description: "Research notes on deep learning, generative models, and representation learning."

# URL for GitHub Pages
url: "https://aliasgharmirhshai.github.io"
baseurl: ""

# GitHub info
github:
  username: aliasgharmirhshai

# Social links
social:
  name: "Ali Asghar Mirhshahi"
  links:
    - https://github.com/aliasgharmirhshai
    - https://www.linkedin.com/in/aliasghar-mirshahi-883b87413/

# Theme options
theme_mode: dark
toc: true
paginate: 10
